### ISSUE TITLE
object ‘as.data.frame.ppp’ is not exported by 'namespace:spatstat'

### ISSUE THREAD

**Issue by rupam007** [spatstat/spatstat#158] opened 2022-08-30 14:37 UTC
Hi, 

I am trying to install the R package: swfscMisc, using install.packages("swfscMisc"). 
But it fails with the error object ‘as.data.frame.ppp’ is not exported by 'namespace:spatstat'. Can you please help?

**Comment by rubak** [comment] 2022-08-30 16:08
I get no such message when trying to install `swfscMisc`. Are you trying to install an old version of the package or using an old version of R? Please state your version of R, `spatstat` and the version of `swfscMisc` you are trying to install, and show the output when you run `install.packages("swfscMisc")`. My output ends with:

```r
* installing *source* package ‘swfscMisc’ ...
** package ‘swfscMisc’ successfully unpacked and MD5 sums checked
** using staged installation
** R
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
** building package indices
** testing if installed package can be loaded from temporary location
** testing if installed package can be loaded from final location
** testing if installed package keeps a record of temporary installation path
* DONE (swfscMisc)
```

Afterwards I can check the installed version with:
```r
> packageVersion("swfscMisc")
[1] ‘1.6’
```

**Comment by rupam007** [comment] 2022-08-30 16:16
I am not specifying any version I try and install the "swfscMisc" package.

 This is what I typed:` install.packages("swfscMisc") `

And this the message I see:
`Installing package into ‘/R/3.6’
(as ‘lib’ is unspecified)
Content type 'application/x-gzip' length 36171 bytes (35 KB)
==================================================
downloaded 35 KB

* installing *source* package ‘swfscMisc’ ...
** package ‘swfscMisc’ successfully unpacked and MD5 sums checked
** using staged installation
** R
** byte-compile and prepare package for lazy loading
Error: object ‘as.data.frame.ppp’ is not exported by 'namespace:spatstat'
Execution halted
ERROR: lazy loading failed for package ‘swfscMisc’
* removing /R/3.6/swfscMisc’
Warning in install.packages :
  installation of package ‘swfscMisc’ had non-zero exit status

The downloaded source packages are in
	‘/tmp/downloaded_packages’`

My R version is `R version 3.6.0`

**Comment by rubak** [comment] 2022-08-30 16:24
R is now in version 4.2, and 3.6.0 was [released in April 2019](https://cran.r-project.org/bin/windows/base/old/), so it is more than 3 years old. That is a long time in software development. It *may* be possible to get `swfscMisc` work together with `spatstat` on such an old version of R, but it will probably be a bit difficult. Do you have no way of updating the version of R you are using? Which version of spatstat do you have installed? You may have to roll back to old versions of both `spatstat` and `swfscMisc` to get them to work together on an old version of R.

**Comment by rupam007** [comment] 2022-08-30 16:38
The spatstat version I have installed is 2.3.4. Is there a way I can download the swfscMisc for the R and spatstat version I currently have? I do not think I have a way to access the most recent version of R

**Comment by rubak** [comment] 2022-08-30 16:50
The problem is that the version of `swfscMisc` that works with the version of `spatstat` you have requires R >= 4.0, so I think you would have to downgrade `spatstat` (which I generally don't recommend) to have an old version spatstat that works with an old version of `swfscMisc`. You can download old versions from here: <https://cran.r-project.org/src/contrib/Archive/spatstat/> and any version < 2.0 probably works with `swfscMisc` <= 1.3 which you can download from here: <https://cran.r-project.org/src/contrib/Archive/swfscMisc/>. I think your old R version is automatically trying to download this old version of `swfscMisc`, so you may be able to get the two packages installed side by side simply by these two commands (assuming you have downloaded spatstat 1.64-1 and put in the current working directory of R):
```r
install.packages("spatstat_1.64-1.tar.gz", repos = NULL)
install.packages("swfscMisc")
```
Of course this may conflict with a bunch of other packages you have installed and give you other headaches. Good luck.

**Closed** 2022-08-31 07:18 UTC
