### ISSUE TITLE
New test failure on i386 since 1.60

### ISSUE THREAD

**Issue by ginggs** [spatstat/spatstat#110] opened 2019-08-12 12:58 UTC
Hi, I'm seeing the new test failure below on i386 since 1.60.  The i386 architecture has 80-bit floating point precision, where other architectures like amd64, ARM and POWER have 64-bit.

Can this test be made more robust against variations in floating point precision?
```
discrepancy in isotropic edge correction at interior point of rectangle is 2.22e-16, within tolerance of 1e-06
discrepancy in isotropic edge correction near corner of rectangle is 6.661e-16, within tolerance of 1e-06
discrepancy in isotropic edge correction at interior point of polygon (debug on) is 2.22e-15, within tolerance of 1e-06
discrepancy in isotropic edge correction at interior point of polygon (debug off) is 0.6667, exceeding tolerance of 1e-06
Discrepancies: -0.666666666666667, 6.66133814775094e-16
Error: excessive discrepancy in isotropic edge correction at interior point of polygon (debug off)
Execution halted
```

**Comment by baddstats** [comment] 2019-08-13 01:11
Thanks for alerting us.
This is caused by the optimising compiler rather than the architecture.
I will try to find a more robust fix.

**Comment by baddstats** [comment] 2019-08-13 03:48
I have implemented a tentative fix. 
Please try checking the current development version `spatstat 1.60-1.024` on your system.

**Comment by ginggs** [comment] 2019-08-13 06:02
That worked, thanks!  I now get:
```
discrepancy in isotropic edge correction at interior point of rectangle is 2.22e-16, within tolerance of 1e-06
discrepancy in isotropic edge correction near corner of rectangle is 6.661e-16, within tolerance of 1e-06
discrepancy in isotropic edge correction at interior point of polygon (debug on) is 2.22e-15, within tolerance of 1e-06
discrepancy in isotropic edge correction at interior point of polygon (debug off) is 6.661e-16, within tolerance of 1e-06
```
Full test log is [here](https://objectstorage.prodstack4-5.canonical.com/v1/AUTH_77e2ada1e7a84929a74ba3b87153c0ac/autopkgtest-eoan-ginggs-testing/eoan/i386/r/r-cran-spatstat/20190813_054836_09fc6@/log.gz).

**Comment by baddstats** [comment] 2019-08-13 07:30
Great!
 I will close this issue, but please re-open it if the problem recurs.

**Closed by baddstats** 2019-08-13 07:30 UTC
